name: Standalone

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

env:
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: "**/cpm_modules"
          key: ${{ matrix.os }}-${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: configure
        run: cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Debug -DENABLE_TEST_COVERAGE=OFF -DENABLE_STANDALONE=ON -DENABLE_DOCUMENTATION=OFF

      - name: build
        run: cmake --build build -j4 --target ConcurrencyStandalone

      - name: run on unix-like
        if: startsWith(matrix.os, 'macOS') || startsWith(matrix.os,'ubuntu')
        run: ./build/out/ConcurrencyStandalone

      - name: run on windows
        if: startsWith(matrix.os, 'windows')
        run: ./build/out/Debug/ConcurrencyStandalone.exe

  build-emscripten:
    runs-on: ubuntu-latest
    container: emscripten/emsdk

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: "**/cpm_modules"
          key: emscripten-${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: configure
        run: emcmake cmake -DCMAKE_C_ABI_COMPILED=ON -DCMAKE_CXX_ABI_COMPILED=ON -DEMSCRIPTEN=1 -DCMAKE_BUILD_TYPE=MinSizeRel -S. -Bbuild -DENABLE_TEST_COVERAGE=OFF -DENABLE_STANDALONE=ON -DENABLE_DOCUMENTATION=OFF -DCMAKE_EXECUTABLE_SUFFIX=".html"

      - name: build
        run: cmake --build build -j4 --config Release

      - name: execute
        run: node node --experimental-wasm-threads --experimental-wasm-bulk-memory build/out/ConcurrencyStandalone.js ./build/out/ConcurrencyStandalone.js